### ISSUE TITLE
Concept Verification

### ISSUE THREAD

**Issue by christianj6** [ALLUOS/ALLUOS.github.io#14]
**Description**
In order to assess our operating concept, we should interview or otherwise obtain feedback from domain professionals.

**Acceptance Criteria**
- [x] Provide domain professional(s) with summary of application requirements that they can assess the concept.
- [ ] Organize this feedback and present in a 10-15 minute presentation during an upcoming meeting.
- [ ] The presentation should include a list of recommendations for adjusting the application or concept if necessary.

**Comment by LangLoffelLako** [comment]
The acceptance criteria are not up to date, as we decided to replace the verification with a review of the SRS file by Tobias. Or is something else meant by this?

**Comment by christianj6** [comment]
Hi. An oversight. You are correct. I will update this now.

**Comment by LangLoffelLako** [comment]
Thanks
