### ISSUE TITLE
Codebase Overview (for Group 3)

### ISSUE THREAD

**Issue by christianj6** [ALLUOS/ALLUOS.github.io#18]
**Description**
Group 3 requires a comprehensive overview of the application architecture to make more efficient navigation of the codebase for test design purposes.

**Acceptance Criteria**
- [x] Shows relationship between main modules, classes, and functions.
- [x] Provides information on function input/returns

**Comment by LangLoffelLako** [comment]
Fulfilled by https://github.com/ALLUOS/app/pull/37#issue-441917246
