### ISSUE TITLE
improve adaptability

### ISSUE THREAD

**Issue by christianj6** [ALLUOS/ALLUOS.github.io#34]
**Description**
To improve the application's ability to adapt to user performance and implicitly, their language proficiency, we must expand and make more sophisticated the adaptability module, preferably with recourse to machine learning methodologies to both enhance the module's functionality and align with the overall project goal of an 'ai-assisted' agent. The first step is to develop a comprehensive and feasible proposal for this improvement.

**Assumptions**
- the application's codebase supports modular insertion of an improved adaptability module with little refactoring overhead

**Out of Scope**
- implementation of the improved adaptability module

**Acceptance Criteria**
- [ ] 5 minute presentation with detailed proposal for improvement of the adaptability module
- [ ] proposal and coordination with @test for how the updated module can be evaluated
- [ ] information on prior research which justifies the proposed approach
- [ ] information on any necessary adjustments to the current application infrastructure or database schema, including additional data which may be required to realize the proposal

**Additional Information**
Information on the current adaptive module can be found [here](https://alluos.github.io/2020/05/02/implementation.html#adaptive)

**Comment by christianj6** [comment]
**Description**
To improve the application's ability to adapt to user performance and implicitly, their language proficiency, we must expand and make more sophisticated the adaptability module, preferably with recourse to machine learning methodologies to both enhance the module's functionality and align with the overall project goal of an 'ai-assisted' agent. The first step is to develop a comprehensive and feasible proposal for this improvement.

**Assumptions**
- the application's codebase supports modular insertion of an improved adaptability module with little refactoring overhead

**Out of Scope**
- implementation of the improved adaptability module

**Acceptance Criteria**
- 10 minute presentation with detailed proposal for improvement of the adaptability module
- proposal and coordination with @test for how the updated module can be evaluated
- information on prior research which justifies the proposed approach
- information on any necessary adjustments to the current application infrastructure or database schema, including additional data which may be required to realize the proposal

**Additional Information**

**Comment by LangLoffelLako** [comment]
Is the 10 minute presentation meant to be the presentation that is going to take place on our next monday meeting?
I am currently working out a draft for an adaptive module.

**Comment by christianj6** [comment]
Admittedly, the upcoming pitch activity was conceived after this proposal task. It is acceptable to use this presentation as a substitute for the pitch activity discussed last meeting, given that there is agreed demand for an update to the adaptive module. I have updated the time limit to reflect this change.
